name: native_geofence
description: Battery efficient Flutter Geofencing that uses native iOS and Android APIs.
version: 2.0.0
homepage: https://steffaanus.com
repository: https://github.com/steffaanus/native_geofence

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^26.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.steffaanus.native_geofence
        pluginClass: NativeGeofencePlugin
      ios:
        pluginClass: NativeGeofencePlugin
